server:
  port: 9090
spring:
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
    consumer:
      group-id: ollama-job-group
      auto-offset-reset: earliest
  ai:
    ollama:
      base-url: http://192.168.124.7:11434
      chat:
        options:
          model: llama3.1:latest # Or whichever model you are running locally